//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *PodCleanupPolicy) DeepCopyInto(out *PodCleanupPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new object of the same type and copies all fields from this object.
func (in *PodCleanupPolicy) DeepCopy() *PodCleanupPolicy {
	if in == nil {
		return nil
	}
	out := new(PodCleanupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *PodCleanupPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *PodCleanupPolicyList) DeepCopyInto(out *PodCleanupPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodCleanupPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new object of the same type and copies all fields from this object.
func (in *PodCleanupPolicyList) DeepCopy() *PodCleanupPolicyList {
	if in == nil {
		return nil
	}
	out := new(PodCleanupPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *PodCleanupPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *PodCleanupPolicySpec) DeepCopyInto(out *PodCleanupPolicySpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PodStatuses != nil {
		in, out := &in.PodStatuses, &out.PodStatuses
		*out = make([]corev1.PodPhase, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a new object of the same type and copies all fields from this object.
func (in *PodCleanupPolicySpec) DeepCopy() *PodCleanupPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PodCleanupPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *PodCleanupPolicyStatus) DeepCopyInto(out *PodCleanupPolicyStatus) {
	*out = *in
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new object of the same type and copies all fields from this object.
func (in *PodCleanupPolicyStatus) DeepCopy() *PodCleanupPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PodCleanupPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
